---
version: 2.1

orbs:
  terraform: twdps/terraform@dev:latest

# ==== global pipeline parameters

parameters:
  terraform-version:
    description: terraform version for all jobs
    type: string
    default: "1.0.6"
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: secrethub run -- /bin/sh -eo pipefail

# ==== triggers

# git push: deploy sandbox
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

# git tag: release 
on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment: 
    description: generate environment credentials and configuration from templates
    parameters:
      env:
        type: string
        default: ''
    steps:
      - run:
          name: set ~/.terraformrc
          command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.env >> environment variables
          command: secrethub inject -i environments/<< parameters.env >>.auto.tfvars.json.tpl -o << parameters.env >>.auto.tfvars.json

jobs:

  test-vpc:
    docker:
      - image: twdps/circleci-infra-aws:alpine-1.0.0
    shell: secrethub run -- /bin/sh -eo pipefail
    parameters:
      env:
        type: string
        default: ''
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          env: << parameters.env >>
      - run:
          name: test << parameters.env >> configuration
          environment:
            TEST_ENV: << parameters.env >>
          command: bash scripts/vpc.test.sh << parameters.env >>

workflows:
  version: 2
  lab-platform-vpc-pipeline:

    jobs:
      # git push: deploy sandbox
      - terraform/plan:
          name: sandbox-change-plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: sandbox
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: sandbox
          filters: *on-push-main

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-main

      - terraform/apply:
          name: sandbox-change-apply
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: sandbox
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: sandbox
          requires:
            - approve-sandbox-changes
          filters: *on-push-main

      - test-vpc:
          name: test-sandbox-configuration
          context: << pipeline.parameters.context >>
          env: sandbox
          requires:
            - sandbox-change-apply
          filters: *on-push-main

      # git tag: deploy preview
      - terraform/plan:
          name: preview-change-plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: preview
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: preview
          filters: *on-tag-main

      - approve-preview-changes:
          type: approval
          requires:
            - preview-change-plan
          filters: *on-tag-main

      - terraform/apply:
          name: preview-change-apply
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: preview
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: preview
          requires:
            - approve-preview-changes
          filters: *on-tag-main

      - test-vpc:
          name: test-preview-configuration
          context: << pipeline.parameters.context >>
          env: preview
          requires:
            - preview-change-apply
          filters: *on-tag-main


# ---
# version: 2.1

# orbs:
#   terraform: feedyard/terraform@0.6.0

# # git push: deploy sandbox
# on-push-master: &on-push-master
#   branches:
#     only: /master/
#   tags:
#     ignore: /.*/

# # git tag: release pipeline, currently just - preview -
# on-tag-master: &on-tag-master
#   branches:
#     ignore: /.*/
#   tags:
#     only: /.*/


# commands:

#   set-environment: 
#     description: generate environment credentials and configuration from templates
#     parameters:
#       env:
#         type: string
#         default: ''
#     steps:
#       - run:
#           name: set ~/.terraformrc
#           command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
#       - run:
#           name: set << parameters.env >> environment variables
#           command: secrethub inject -i environments/<< parameters.env >>.auto.tfvars.json.tpl -o << parameters.env >>.auto.tfvars.json

#   test-configuration:
#     description: awspec tests of the resulting infrastructure resources
#     parameters:
#       env:
#         type: string
#         default: ''
#     steps:
#       - run:
#           name: test << parameters.env >> configuration
#           environment:
#             TEST_ENV: << parameters.env >>
#           command: secrethub run -- bash scripts/vpc.test.sh << parameters.env >>

# workflows:
#   version: 2
#   lab-platform-vpc-pipeline:

#     jobs:
#       - terraform/plan:
#           name: sandbox-change-plan
#           context: twdps-core-labs-team
#           shell: secrethub run -- /bin/sh -eo pipefail
#           workspace: sandbox
#           before-terraform:
#             - set-environment:
#                 env: sandbox
#           filters: *on-push-master

#       - approve-sandbox-changes:
#           type: approval
#           requires:
#             - sandbox-change-plan
#           filters: *on-push-master

#       - terraform/apply:
#           name: sandbox-change-apply
#           context: twdps-core-labs-team
#           shell: secrethub run -- /bin/sh -eo pipefail
#           workspace: sandbox
#           before-terraform:
#             - set-environment:
#                 env: sandbox
#           after-terraform:
#             - test-configuration:
#                 env: sandbox
#           requires:
#             - approve-sandbox-changes
#           filters: *on-push-master

#       # release 
#       - terraform/plan:
#           name: preview-change-plan
#           context: twdps-core-labs-team
#           shell: secrethub run -- /bin/sh -eo pipefail
#           workspace: preview
#           before-terraform:
#             - set-environment:
#                 env: preview
#           filters: *on-tag-master

#       - approve-preview-changes:
#           type: approval
#           requires:
#             - preview-change-plan
#           filters: *on-tag-master

#       - terraform/apply:
#           name: preview-change-apply
#           context: twdps-core-labs-team
#           shell: secrethub run -- /bin/sh -eo pipefail
#           workspace: preview
#           before-terraform:
#             - set-environment:
#                 env: preview
#           after-terraform:
#             - test-configuration:
#                 env: preview
#           requires:
#             - approve-preview-changes
#           filters: *on-tag-master
      