---
version: 2.1

orbs:
  terraform: twdps/terraform@0.4.0

# ==== global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: secrethub run -- /bin/sh -eo pipefail
  terraform-version:
    description: terraform version for all jobs
    type: string
    default: "1.1.2"
  executor-image:
    description: use this image for local job definitions
    type: string
    default: twdps/circleci-infra-aws:alpine-1.3.0

# ==== triggers

# git push: deploy sandbox
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

# git tag: release 
on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment: 
    description: generate environment credentials and configuration from templates
    parameters:
      env:
        type: string
        default: ''
    steps:
      - run:
          name: set ~/.terraformrc
          command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.env >> environment variables
          command: secrethub inject -i environments/<< parameters.env >>.auto.tfvars.json.tpl -o << parameters.env >>.auto.tfvars.json

jobs:

  test-vpc:
    docker:
      - image: << pipeline.parameters.executor-image >>
    shell: << pipeline.parameters.shell-options >>
    parameters:
      env:
        type: string
        default: ''
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          env: << parameters.env >>
      - run:
          name: test << parameters.env >> configuration
          environment:
            TEST_ENV: << parameters.env >>
          command: bash scripts/vpc.test.sh << parameters.env >>

workflows:
  version: 2
  lab-platform-vpc-pipeline:

    jobs:
      # git push: deploy sandbox
      - terraform/plan:
          name: sandbox-change-plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: sandbox
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: sandbox
          filters: *on-push-main

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-main

      - terraform/apply:
          name: sandbox-change-apply
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: sandbox
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: sandbox
          requires:
            - approve-sandbox-changes
          filters: *on-push-main

      - test-vpc:
          name: test-sandbox-configuration
          context: << pipeline.parameters.context >>
          env: sandbox
          requires:
            - sandbox-change-apply
          filters: *on-push-main

      # git tag: deploy preview
      - terraform/plan:
          name: preview-change-plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: preview
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: preview
          filters: *on-tag-main

      - approve-preview-changes:
          type: approval
          requires:
            - preview-change-plan
          filters: *on-tag-main

      - terraform/apply:
          name: preview-change-apply
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: preview
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                env: preview
          requires:
            - approve-preview-changes
          filters: *on-tag-main

      - test-vpc:
          name: test-preview-configuration
          context: << pipeline.parameters.context >>
          env: preview
          requires:
            - preview-change-apply
          filters: *on-tag-main


  nightly-test-run:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test-vpc:
          name: nightly-sandbox
          context: << pipeline.parameters.context >>
          env: sandbox
          
      - test-vpc:
          name: nightly-preview
          context: << pipeline.parameters.context >>
          env: preview