---
version: 2.1
setup: true
 
orbs:
  continuation: circleci/continuation@0.1.2

# git push: deploy sandbox
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

# git tag: release pipeline, currently just - preview -
on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

jobs:
  terraform:
    parameters:
      env:
        description: generate terraform deployment pipeline for environment passed by this parameter
        type: string
    executor: continuation/default

    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/deploy.yml
          parameters: "{ \"env\": \"<< parameters.env >>\" }"

workflows:
  setup:
    jobs:

      - terraform:
          name: deploy-sandbox
          env: sandbox
          filters: *on-push-master

      - terraform:
          name: deploy-preview
          env: preview
          filters: *on-tag-master
