---
version: 2.1
setup: true

orbs:
  continuation: circleci/continuation@0.1.2

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

jobs:
  terraform:
    parameters:
      env:
        description: env value to use for generated pipeline
        type: string
        default: ''
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: generate terraform-deploy circle pipeline passed environment parameter >> environment.yml
          command: bash deploy.sh << parameters.env >>
      - continuation/continue:
          configuration_path: environment.yml # use newly generated environment deployment pipeline to continue

workflows:
  version: 2
  lab-platform-vpc-pipeline:
    jobs:
      - terraform:
          name: deploy-sandbox
          env: sandbox
          filters: *on-push-master
