---
version: 2.1
setup: true
 
orbs:
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    parameters:
      env:
        description: generate deployment pipeline for environment passed by this parameter
        type: string

    executor: continuation/default
    steps:
      - checkout
      - run:
          name: generate terraform-deploy pipeline from passed environment parameter >> environment.yml
          command: bash .circleci/deploy.sh << parameters.env >>
      - continuation/continue:
          configuration_path: environment.yml

workflows:
  setup:
    jobs:
      - setup:
          name: deploy-sandbox
          env: sandbox
          filters: 
            branches:
              only: /master/
            tags:
              ignore: /.*/
