---
version: 2.1

orbs:
  terraform: feedyard/terraform@0.3.0

on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

on-tag-master: &on-tag-master
  branches:
    ignore: /.*/
  tags:
    only: /.*/

workflows:
  version: 2
  lab-platform-vpc-pipeline:

    jobs:
      - terraform/plan:
          name: sandbox-change-plan
          context: twdps-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
          filters: *on-push-master

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-master

      - terraform/apply:
          name: sandbox-change-apply
          context: twdps-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
                  secrethub inject -i tpl/nonprod.test.sh.tpl -o nonprod.test.sh
          after-terraform:
            - run:
                name: test sandbox account changes
                environment:
                  TEST_ENV: sandbox
                command: secrethub run -- bash nonprod.test.sh sandbox
          requires:
            - approve-sandbox-changes
          filters: *on-push-master

      # git tag - release pipeline

      # release preview cluster vpc
      - terraform/plan:
          name: preview-change-plan
          context: twdps-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: preview
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/preview.auto.tfvars.json.tpl -o preview.auto.tfvars.json
          filters: *on-tag-master

      - approve-preview-changes:
          type: approval
          requires:
            - preview-change-plan
          filters: *on-tag-master

      - terraform/apply:
          name: preview-change-apply
          context: twdps-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: preview
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/preview.auto.tfvars.json.tpl -o preview.auto.tfvars.json
                  secrethub inject -i tpl/nonprod.test.sh.tpl -o nonprod.test.sh
          after-terraform:
            - run:
                name: test preview account changes
                environment:
                  TEST_ENV: preview
                command: secrethub run -- bash nonprod.test.sh preview
          requires:
            - approve-preview-changes
          filters: *on-tag-master
      
      # repeat tag release sections for each desired environment
      #
      # typical DI pipeline is: sandbox > preview > nonprod > prod > management

      - tear-down-lab-vpcs:
          type: approval
          filters: *on-push-master

      - approve-teardown-vpc:
          type: approval
          requires:
            - tear-down-lab-vpcs
          filters: *on-push-master

      - terraform/destroy:
          name: sandbox lab vpc teardown
          context: twdps-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: sandbox
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/sandbox.auto.tfvars.json.tpl -o sandbox.auto.tfvars.json
          requires:
            - approve-teardown-vpc
          filters: *on-push-master

      - terraform/destroy:
          name: preview lab vpc teardown
          context: twdps-di
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: preview
          before-terraform:
            - run:
                name: generate environmental configuration and credentials from templates
                command: |
                  secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
                  secrethub inject -i tpl/preview.auto.tfvars.json.tpl -o preview.auto.tfvars.json
          requires:
            - approve-teardown-vpc
          filters: *on-push-master
