---
version: 2.1

orbs:
  terraform: twdps/terraform@0.4.0
  # used for github-release-notes feature
  executor-tools: twdps/executor-tools@0.2.0

# ==== global pipeline parameters

parameters:
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: secrethub run -- /bin/sh -eo pipefail
  terraform-version:
    description: terraform version for all jobs
    type: string
    default: "1.1.3"
  executor-image:
    description: use this image for local job definitions
    type: string
    default: twdps/circleci-infra-aws:alpine-1.3.0

# ==== triggers

# git push: deploy sandbox
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

# git tag: release 
on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment: 
    description: generate environment credentials and configuration from templates
    parameters:
      cluster:
        description: cluster environment
        type: string
    steps:
      - run:
          name: set ~/.terraformrc
          command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.env >> environment variables
          command: secrethub inject -i environments/<< parameters.cluster >>.auto.tfvars.json.tpl -o << parameters.cluster >>.auto.tfvars.json

jobs:

  validate-vpc:
    docker:
      - image: << pipeline.parameters.executor-image >>
    shell: << pipeline.parameters.shell-options >>
    parameters:
      cluster:
        description: cluster vpc configuration to validate
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - set-environment:
          cluster: << parameters.env >>
      - run:
          name: test << parameters.cluster >> configuration
          environment:
            TEST_ENV: << parameters.cluster >>
          command: bash scripts/vpc.test.sh << parameters.cluster >>

workflows:
  version: 2
  lab-platform-vpc-pipeline:

    jobs:
      # git push: deploy sandbox
      - terraform/plan:
          name: sandbox-change-plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: sandbox
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                cluster: sandbox
          filters: *on-push-main

      - approve-sandbox-changes:
          type: approval
          requires:
            - sandbox-change-plan
          filters: *on-push-main

      - terraform/apply:
          name: sandbox-change-apply
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: sandbox
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                cluster: sandbox
          requires:
            - approve-sandbox-changes
          filters: *on-push-main

      - validate-vpc:
          name: test-sandbox-vpc-configuration
          context: << pipeline.parameters.context >>
          cluster: sandbox
          requires:
            - sandbox-change-apply
          filters: *on-push-main

      # git tag: deploy preview
      - terraform/plan:
          name: preview-change-plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: preview
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                cluster: preview
          filters: *on-tag-main

      - approve-preview-changes:
          type: approval
          requires:
            - preview-change-plan
          filters: *on-tag-main

      - terraform/apply:
          name: preview-change-apply
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: preview
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                cluster: preview
          requires:
            - approve-preview-changes
          filters: *on-tag-main

      - validate-vpc:
          name: test-preview-vpc-configuration
          context: << pipeline.parameters.context >>
          cluster: preview
          requires:
            - preview-change-apply
          filters: *on-tag-main

  generate-release-notes:
    jobs:
      - executor-tools/release:
          name: release-lab-platform-vpc
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          filters: *on-tag-main

  # nightly vpc configuration validation
  nightly-vpc-configuration-validation:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - validate-vpc:
          name: nightly-sandbox-vpc-validation
          context: << pipeline.parameters.context >>
          cluster: sandbox 
      - validate-vpc:
          name: nightly-preview-vpv-validation
          context: << pipeline.parameters.context >>
          cluster: preview
